### ISSUE TITLE
Difference between papers

### ISSUE THREAD

**Issue by vedantc6** [cesc-park/attend2u#11]
Hi @cesc-park 
If I am correct, the only difference between CVPR and TPAMI papers is use of data sets. Both use the same CSMN architecture.
Can you or someone validate this?

**Comment by cesc-park** [comment]
The dataset is different and contains partial changes. 
The difference between the TPAMI and CVPR versions is in the CNN structure(shallow and wide cnn / deep CNN).
The current code is the CVPR version, and the hyperparameters are set to run easily.
You can use the same hyperparameters as CVPR by modifying them.

**Comment by vedantc6** [comment]
Thanks a lot!
