### ISSUE TITLE
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by robinsdeepak** [cesc-park/attend2u#13]
Hey, I'm getting error while training the data after extraction, Can you help me with it?
![Capture](https://user-images.githubusercontent.com/42184498/59392837-c0287b00-8d96-11e9-85f7-b476e0506d95.JPG)

**Comment by ecustWallace** [comment]
I guess it's because your cudatoolkit is 9.* or 10.*. If you use anaconda, you can simply:
`conda install cudatoolkit==8.0` or some other version.

Or instead, you can use an updated tensorflow like `conda install tensorflow-gpu==1.12.0rc2`.

**Comment by riven314** [comment]
@ecustWallace 
Thanks for the address
I saw from requirements.txt that the source code requires tensorflow-gpu version 1.1.0 to run.
Does tensorflow-gpu version 1.12 actually work for this source code?
