### ISSUE TITLE
about the validation dataset part?

### ISSUE THREAD

**Issue by 201528014227051** [cesc-park/attend2u#5]
In papar's EXperiments part, said "we randomly split the dataset into 90% for training, 5k posts for test and the rest for validation" but I read the code and found the dataset is parted into train.txt test1.txt and test2.txt, but the text2.txt is not used in code, Did I miss something? 
looking forward to your reply.

**Comment by cesc-park** [comment]
Sorry for the late reply. You should not confuse test2 with validation. Test2 is a test set made to obtain the "split by posts" result of Table 3 in the paper.

**Comment by 201528014227051** [comment]
thanks for reply, i know it.
