### ISSUE TITLE
about  superscript a and c

### ISSUE THREAD

**Issue by bidongqinxian** [cesc-park/attend2u#6]
In your paper，I‘ve read the CSMN model.I have trouble with the understanding of superscript a and c，would you mind telling me what the porpose of  add superscript a and c to the image memory vector and the user context memory vector?Thanks a lot!

**Comment by cesc-park** [comment]
References to the "End-To-End Memory Networks, Sukhbaatar et al" paper will help you understand. As can be seen in the paper, the difference between a and c is a subscript that identifies each matrix that projects into input memory and output memory.
