### ISSUE TITLE
Pretrained model 문의

### ISSUE THREAD

**Issue by Junhyuk** [cesc-park/attend2u#9]
혹시 Pretrained model 있으면 한번 확인이 가능할지요?? 
개인적으로 돌려보니 생각보다.. GPU 성능이 부족하네요.

부탁드립니다.

junhyuk777.lee@gmail.com

**Comment by cesc-park** [comment]
안녕하세요, 아쉽지만 저희가 보유한 Pretrained model 이 학습된 코드와 공개된 정리된 코드와 다른버전이라 
호환이 되지 않아 제공해드리기 어렵습니다.

공개된 코드와 학습 데이터를 이용해서, GPU에 돌리시면 시간이 오래 걸리셔도 비슷한 성능이 나올것입니다.

감사합니다.
